### ISSUE TITLE
ArgumentException when `var` is used with `in` operator

### ISSUE THREAD

**Issue by XDex** [yavuztor/JsonLogic.Net#30]
When a `var` is used with `in` operator, the following exception is thrown when the var is not present in data.
```
System.ArgumentException
Argument is not enumerable
   at JsonLogic.Net.ObjectExtensions.MakeEnumerable(Object value) in /home/andrei/dev/JsonLogic.Net/JsonLogic.Net/ObjectExtensions.cs:line 23
   at JsonLogic.Net.EvaluateOperators.<>c.<AddDefaultOperations>b__9_34(IProcessJsonLogic p, JToken[] args, Object data) in /home/andrei/dev/JsonLogic.Net/JsonLogic.Net/EvaluateOperators.cs:line 233
   at JsonLogic.Net.JsonLogicEvaluator.Apply(JToken rule, Object data) in /home/andrei/dev/JsonLogic.Net/JsonLogic.Net/JsonLogicEvaluator.cs:line 29
   at JsonLogic.Net.UnitTests.JsonLogicTests.Apply(String argsJson, Object expectedResult) in /home/andrei/dev/JsonLogic.Net/JsonLogic.Net.UnitTests/JsonLogicTests.cs:line 170
```

Failing test input that reproduces the issue:
```
[InlineData("{`in`:[`/homePage`,{`var`:`page.url`}]}", false)]
```

**Comment by XDex** [comment]
Fixed in #31 and released in v.1.1.11
@yavuztor Thank you so much for the quick turnaround on releasing the fix!
